spring.application.name=mes

## Datasource (???? ?? ?? ? ?? ???? ??)
# 1. ??? ???? ??
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 2. ?? DB ?? (Oracle XE ?? ?? ???)
# ?? XE? ???? 'xe' ?? 'orcl' ? ??? SID? ??? ???.
spring.datasource.url=jdbc:oracle:thin:@localhost:1522:xe

# 3. ?? DB ???/?? (?? ??? ???? ???/??? ?????)
# ?? ??? ??? system / 1234 (?? oracle) ?? ?? ???.
spring.datasource.username=board
spring.datasource.password=board

# HikariCP ??
spring.datasource.hikari.maximum-pool-size=10

## Mybatis ??
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.aio.mes
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-handlers-package=com.aio.mes.mybatis

## ?? ??? ??
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ??? ?? (????? ?? ? ? ??? ?? ????? ?? ????)
upload.path.windows=C:/image-uploads/
upload.path.linux=/home/user/image-uploads/